// Current corpus content pointer — consumed at runtime (see App.tsx).
// Generated by scripts/record-corpus-sync.mjs on each sync; do not edit by hand.
// Full sync history (per-sync commit + affected sections) lives in ./corpus-sync-log.jsonl.

export const CORPUS_VERSION = 'v0.50.0';

export const CORPUS_BRANCH = 'development';

export const CORPUS_COMMIT = 'd2fb48d7df10a49ddc66f2ffcd149a45e2529c12';
