// Current corpus content pointer — consumed at runtime (see App.tsx).
// Generated by scripts/record-corpus-sync.mjs on each sync; do not edit by hand.
// Full sync history (per-sync commit + affected sections) lives in ./corpus-sync-log.jsonl.

export const CORPUS_VERSION = 'v0.49.0';

export const CORPUS_BRANCH = 'development';

export const CORPUS_COMMIT = '904d1676982db7a7d82d11418af1add7a6f3b414';
